name: Delete Files
description: Deletes Files
branding:
  icon: x
  color: gray-dark
inputs:
  directory:
    description: Parent directory (optional)
    required: false
  delete:
    description: Files to delete
    required: false
  delete-if-empty:
    description: Directories to delete if they are empty
    required: false
runs:
  using: composite
  steps:        

    - shell: bash
      env:
        DIRECTORY: ${{ inputs.directory }}
        DELETE: ${{ inputs.delete }}
        DELETE_IF_EMPTY: ${{ inputs.delete-if-empty }}
      run: |
        DELETE=$(echo "$DELETE" | awk 'NF')
        DELETE_IF_EMPTY=$(echo "$DELETE_IF_EMPTY" | awk 'NF')

        if [[ ! -z "$DELETE" ]]; then
          if [[ ! -z "$DIRECTORY" ]]; then
            DELETE=$(echo "$DELETE" | awk -v prefix="$DIRECTORY/" '{print prefix $0}')
          fi
          eval "rm -rf $(echo "$DELETE" | awk '{printf "%s ", "'\''" $0 "'\''"} END {print ""}')"
        fi

        if [[ ! -z "$DELETE_IF_EMPTY" ]]; then
          if [[ ! -z "$DIRECTORY" ]]; then
            DELETE_IF_EMPTY=$(echo "$DELETE_IF_EMPTY" | awk -v prefix="$DIRECTORY/" '{print prefix $0}')
          fi
          eval "rmdir --ignore-fail-on-non-empty $(echo "$DELETE_IF_EMPTY" | awk '{printf "%s ", "'\''" $0 "'\''"} END {print ""}')"
        fi
